
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    #hostname: localhost
    hostname: ${eureka.instance.hostname:localhost}  # Automatically uses the system's hostname or defaults to localhost

  microservice:
     payment-service:
      endpoints:
       endpoint:
        uri :http://PaymentService/payment/doPayment
     orderservice:
      endpoints:
       endpoint:
        uri :http://orderservice/order/bookOrder  
